ndn/data.go
ndn/data_test.go
ndn/security/signature.go

Spec: https://redmine.named-data.net/projects/ndn-tlv/wiki/NullSignature
With this patch, YaNFD and NDN-DPDK will become interoperable. Hope you'll accept.

Decode Data with NullSignature

---

.github/workflows/build.yml
face/impl/pcap.go
face/impl/pcap_disabled.go
face/impl/pcap_enabled.go
face/impl/syscalls_darwin.go
face/impl/syscalls_windows.go
face/multicast-ethernet-transport.go

It is sometimes desirable to build with cgo disabled, so that the result binary is cross platform.
For example, a non-cgo binary built for Linux would work on any Linux distribute, as it has no dependency on C libraries such as libpcap.
Moreover, a non-cgo binary can be packaged as a minimal-size Docker image that only contains the binary itself and nothing else.

Allow building without cgo

---

face/init.go
face/unicast-tcp-transport.go
ndn/uri.go

PR Copied from `https://github.com/eric135/YaNFD/pull/1`. 
Changes: 
- In ndn/uri.go, GetURIType() would return type uriType, which wasn't visible outside the module. To make this method functional, the uriType has been renamed to URIType.
- Added Unicast TCP face to face/unicast-tcp-transport.go.
- Added associated TCP logic in ndn/uri.go.
Potentially Harmful Decisions:
- TCP is connection based, so connections can be explicitly closed (unlike UDP). This raises the question of whether to give each interface an expirationTime for TCP Unicast. I've opted to add an expiration time, with a default value of one hour. This mirrors the current settings for UDP, but not Ethernet.

Implement TCP Unicast Face Logic

---

cmd/yanfd/main.go

Also, change faces.websocket.enabled default to match sample config.
---
This change fixes `/localhop/nfd` prefix registration functionality.

yanfd: load mgmt module configuration

---

face/udp-listener.go

When `UDPListener` receives a packet, it constructs LinkService, then performs these two actions:
1. The current packet is passed to LinkService, which may further pass it to forwarding.
2. The face is added to `FaceTable`, which assigns it a FaceID.
Previously, action 1 is performed before action 2.
This causes the first packet to be dropped by forwarding, with the following error message:
```
ERROR[0002] [FwThread-0] Non-existent incoming FaceID=0 for Interest=/localhost - DROP
```
This change swaps the order, so that action 1 is performed after action 2.
This ensures FaceID is already assigned when forwarding sees the packet, so that the packet can be processed successfully.

face: ensure first UDP packet has incoming FaceID

---

cmd/yanfd/main.go
yanfd.toml.sample

According to README.md:
> YaNFD's configuration is split into two components: startup configuration and runtime configuration.
> Startup configuration for YaNFD is performed via a TOML file
However, the existing program does not fulfill this design: there are several command line flags that are part of the startup configuration, which existed outside of the TOML file.
This PR partially restores the design intention by deprecating `-disable-ethernet` and `-disable-unix` flags and reproducing their functionality in the TOML file.

yanfd: disable Ethernet/Unix transports via config file

---

face/tcp-listener.go

Currently, if TCPListener fails to start a listening socket, its Close function may panic.
So far this condition is persistently happening on Windows for *Loopback Pseudo-Interface 1*.
The log is as follows:
```shell
$ ./yanfd.exe -config yanfd.toml.sample -disable-unix -disable-ethernet
[34m  INFO[0m[0000] [Main] Starting YaNFD    
[34m  INFO[0m[0000] [NullTransport, FaceID=0, RemoteURI=null://, LocalURI=null://] state: Down -> Up
[34m  INFO[0m[0000] [Management] Starting management
[34m  INFO[0m[0000] [InternalTransport, FaceID=0, RemoteURI=internal://, LocalURI=internal://] state: Down -> Up
[31m ERROR[0m[0000] [Main] Unable to create MulticastUDPTransport for fe80::d021:b241:d777:cb67%vEthernet (WSL) on vEthernet (WSL): Unable to create send connection to group address: dial …
```

face: fix panic in TCPListener.Close

---

ndn/data.go
ndn/data_test.go
ndn/signature-info.go

This PR allows the forwarder to passthrough Data packets containing *ValidityPeriod* field, commonly used in NDN certificates.
NDN Testbed Root X3 certificate is used as test case.

ndn: recognize ValidityPeriod in SignatureInfo

---

fw/bestroute.go
fw/strategy.go
fw/thread.go

Currently, if the forwarder receives an Interest on a face that happens to be a FIB nexthop, the multicast strategy would send this Interest back to where it came from, and the best-route strategy may send it back if the FIB nexthop happens to be the lowest cost route.
This condition frequently occurs when the application is using a sync protocol.
While this would not affect application operations in a correctly implemented library, those Interests are unnecessary overhead.
This PR updates forwarding logic and strategies so that they do not send an Interest back to the incoming face, unless the face is labeled as ad hoc wireless.

fw: don't send Interest back to inFace

---

ndn/interest_test.go
ndn/name.go
ndn/name_test.go

According to NDN Packet Format, NameComponent (except ImplicitSha256DigestComponent and ParametersSha256DigestComponent) can have TLV-LENGTH==0.

ndn: accept NameComponent with TLV-LENGTH==0

---

mgmt/cs.go
mgmt/thread.go
ndn/mgmt/cs-status.go

This minimal implementation allows nfd-status-http-server to work with
YaNFD. The dataset contains valid NCsEntries counter, but other fields
are bogus.

mgmt: minimal cs/info dataset

---

face/ndnlp-link-service.go
mgmt/face.go

There was an error in `faceDataset.Flags` assignment, causing a face with *local-fields* flag (such as one created by NLSR) to instead show *lp-reliability* flag in `nfdc face` output.

mgmt: fix face dataset Flags field

---

table/rib.go

Separate the concept of `RibTable` from `RibEntry`.
Fix a logic bug in `pruneIfEmpty`.
The bug was on this line:
```go
if child == r {
```

table: RIB code cleanup & bugfix

---

cmd/yanfdui/server/server.go
executor/yanfd.go
ndn/name.go
table/fib-strategy-hashtable.go
table/fib-strategy-hashtable_test.go
table/fib-strategy-tree.go
table/init.go
utils/comparison/comparison.go
yanfd.toml.sample

Implement FIB table based on hash table algorithm from Won et al 2013.
A Python implementation of the algorithm can be found [here](https://gist.github.com/danningyu/8724a4b1894f15ea67cd0eb6e4db62b8) if one prefers reading code in Python to understand the algorithm first.
Unit test coverage of this new algorithm is at 100%.

FIB Table: Hashtable Implementation (from danningyu/YaNFD#7)

---

fw/thread.go
table/pit-cs-tree.go
table/pit-cs-tree_test.go
table/pit-cs.go

pit-cs: Remove extra goroutine and Mutex

---

executor/profiler.go
executor/yanfd.go
face/internal-transport.go
face/link-service.go
face/multicast-udp-transport.go
face/ndnlp-link-service.go
face/null-link-service.go
face/null-transport.go
face/stream-transport.go
face/table.go
face/tcp-listener.go
face/transport.go
face/udp-listener.go
face/unicast-tcp-transport.go
face/unicast-udp-transport.go
face/unix-stream-listener.go
face/unix-stream-transport.go
face/web-socket-listener.go
face/web-socket-transport.go
fw/thread.go
mgmt/face.go
table/pit-cs.go

Rework face API and fix transports

---

Makefile
README.md

We don't have ethernet face anymore, so don't need this at the moment.

docs: disable CGO and update docs

---

.github/workflows/build.yml
.github/workflows/test.yml
fw/face/ndnlp-link-service.go

spec.ReadPacket validates the digest on Interests if app params are present. This is unnecessary for forwarding.

fw: do not validate packets after parse

---

std/security/asym-signer.go
std/security/ecc-signer.go
std/security/ed-signer.go
std/security/rsa-signer.go
std/security/signers_test.go

security: Add ed25519 signer

---

fw/face/ndnlp-link-service.go

1. Overhead calculation was broken
2. Outgoing framents were incorrect
3. Fix memleak when fragments are missed (ring buffer for reassembly instead of map)

Fix NDNLP fragment reassembly

---

dv/config/config.go
dv/dv/advert_data.go
dv/dv/advert_sync.go
dv/dv/router.go
dv/table/neighbor_table.go
fw/defn/pkt.go
fw/dispatch/face.go
fw/face/internal-transport.go
fw/face/ndnlp-link-service.go
fw/fw/thread.go
fw/mgmt/nlsr_readvertiser.go
fw/mgmt/rib.go
fw/table/rib.go
std/encoding/init.go
std/ndn/mgmt_2022/definitions.go
std/ndn/mgmt_2022/mgmt.go
std/ndn/mgmt_2022/persistency.go
std/ndn/mgmt_2022/route.go
tools/nfdc/nfdc.go
tools/nfdc/nfdc_cmd.go
tools/nfdc/nfdc_route.go
tools/putchunks.go

If the first component is /localhop, we do not forward interests received on non-local faces to non-local faces

Implement Localhop

---

dv/config/config.go
dv/dv/advert_data.go
dv/dv/advert_sync.go
dv/dv/table_algo.go
dv/table/neighbor_table.go
dv/table/prefix_table.go
fw/defn/name.go
fw/fw/strategy.go
fw/mgmt/cs.go
fw/mgmt/face.go
fw/mgmt/fib.go
fw/mgmt/forwarder-status.go
fw/mgmt/helpers.go
fw/mgmt/rib.go
fw/mgmt/strategy-choice.go
fw/mgmt/thread.go
std/encoding/name_component.go
std/encoding/name_pattern.go
std/encoding/name_test.go
std/examples/low-level/consumer/main.go
std/examples/wasm/low-level/consumer/main.go
std/ndn/mgmt_2022/mgmt.go
std/object/client_consume.go
std/object/client_consume_seg.go
std/object/client_produce.go
std/sync/svs.go
tools/dvc/dvc.go
tools/nfdc/nfdc_dataset.go
tools/pingclient.go
tools/pingserver.go

append() has some unintuitive behavior due to sharing the underlying array. See the test in the first commit linked below for details:
https://github.com/named-data/ndnd/commit/9ce47e1e3f12d0f73e2617ecf6e1150427398dac#diff-7f7479b24b8bf1c99ac3258e8da6430d23fb052a4e26653d44128913e88cc4a2R338-R346
```golang
// This section illustrates the issue with using append()
// If we have a prefix which has an underlying array larger than the slice itself,
// then subsequent appends will modify the same array. This will overwrite any
// names created from the same prefix.
prefix := utils.WithoutErr(enc.NameFromStr("/a/b/c/z/z/z"))[:3]
name1 := append(prefix, utils.WithoutErr(enc.NameFromStr("d1/e1/f1"))...)
name2 := append(prefix, utils.WithoutErr(enc.NameFromStr("d2/e2/f2"))...)
require.Equal(t, …
```

Add encoding.Name.Append() method

---

std/encoding/name_component.go
std/encoding/name_pattern.go

Strings in go are immutable, so each concat is an allocation.
String builder internally uses unsafe so I expect it's fast (lol)

std: use string builder for Name::String()

---

std/encoding/component.go
std/encoding/name_bench_test.go
std/encoding/name_pattern.go
std/encoding/name_test.go
std/utils/testutils/error.go

Better version of #121
> enc.Name.String() is too slow for usage in map[string]... (since go doesn't support custom keys). Using a cryptographic hash is too expensive and xxhash is not collision free.
`TlvStr()` returns a TLV encoded name string. I realised (bit late) that our encoding is very efficient. Decoding is slightly slower than the earlier version but that's fine since map reads need only encode.
Surprisingly the TLV encode is even faster than just copying the memory over (huh go?)
```
goos: linux
goarch: amd64
pkg: github.com/named-data/ndnd/std/encoding
cpu: AMD EPYC 7702P 64-Core Processor               
BenchmarkNameHash-128                            1000000              1028 ns/op             160 B/op         20 allocs/op
BenchmarkNameStringEncode-128 …
```

std: util to encode TLV to string

---

fw/core/config.go
fw/yanfd.sample.yml
std/engine/client_conf.go

#144 
Checks operating system before choosing socket file.
If on Mac, use /var/run/nfd/nfd.sock
Otherwise, use /run/nfd/nfd.sock
Fixes an issue where Mac gives a permission denied error when trying to create a file in the /run folder.

Switch default socket to /var/run/nfd/nfd.sock on Mac

---

fw/cmd/yanfd.go
fw/defn/uri.go
fw/face/udp-listener.go

Fix #144
Mac cannot have two identical port binds, so create one listener for each interface (this was the old design).

fw: fix UDP listener on macOS

---

std/security/ndncert/challenge_dns.go
std/security/ndncert/challenge_dns_test.go
std/security/ndncert/constants.go
tools/sec/cert_client.go

PR to add the DNS challenge support. It contains two parts: the client implementation and `certcli` support.
The DNS challenge [spec](https://github.com/UCLA-IRL/ndncert/blob/master/DNS-Challenge-Spec.md) tries to do things very similar to Let's Encrypt [dns-01](https://letsencrypt.org/docs/challenge-types/#dns-01-challenge). Currently the testbed root CA already supports this challenge, feel free to test this code against it.
Semi-related implementation decisions I deliberately made:
* No corresponding PROBE: I believe the NDN names derived from DNS names should follow a uniform name convention
* When DNS challenge is chosen, `certcli` skips the PROBE and forces to append the domain name under the CA name (e.g., /ndn/example.org)
* Spec does not define the record TTL, so does …

Introduce DNS Challenge
